extends: airbnb-base
rules:
    func-names: 0
    no-param-reassign: 0
    eol-last: 0
    comma-dangle: 0
    comma-spacing: 0
    vars-on-top: 0
    import/newline-after-import: 0
    no-multi-spaces: 0
    no-else-return: 0
    spaced-comment: 0
    arrow-body-style: 1
    operator-assignment: 1
    no-console: 1
    semi: 1