# API Values
f5oclock-api:
  enabled: true
  secretName: f5oclock-mongouri
  replicaCount: 1
  image:
    repository: fairbanksio/f5oclock-api
    pullPolicy: Always
  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""
  serviceAccount:
    create: true
    name:
  autoscaling:
    enabled: false
    minReplicas: 2
    maxReplicas: 10
    targetCPUUtilizationPercentage: 50
  minAvailable: 1
  podSecurityContext: {}
  securityContext: {}
  service:
    type: ClusterIP
    port: 80
  ingress:
    annotations:
      kubernetes.io/ingress.class: nginx
    enabled: true
    hosts:
    - host: chart-example.local
      paths: []
    tls: []
  resources:
    requests:
      cpu: 10m
  nodeSelector: {}
  tolerations: []
  affinity: {}
  topologySpreadConstraints: []

# Client Values
f5oclock-client:
  enabled: true
  apiURL: "https://pls.change.me"
  replicaCount: 1
  image:
    repository: fairbanksio/f5oclock-client
    pullPolicy: Always
  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""
  serviceAccount:
    create: true
    name:
  autoscaling:
    enabled: false
    minReplicas: 2
    maxReplicas: 10
    targetCPUUtilizationPercentage: 50
  minAvailable: 1
  podSecurityContext: {}
  securityContext: {}
  service:
    type: ClusterIP
    port: 80
  ingress:
    annotations:
      kubernetes.io/ingress.class: nginx
    enabled: true
    hosts:
    - host: chart-example.local
      paths: []
    tls: []
  resources:
    requests:
      cpu: 10m
  nodeSelector: {}
  tolerations: []
  affinity: {}
  topologySpreadConstraints: []

# Scraper Values
f5oclock-scraper:
  enabled: true
  secretName: "f5oclock-mongouri"
  subreddits: 
    - "politics"
  image:
    repository: fairbanksio/f5oclock-scraper
    pullPolicy: IfNotPresent
  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""
  serviceAccount:
    create: true
    name:
  podSecurityContext: {}
  securityContext: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  schedule: "* * * * *"
  restartPolicy: Never
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  backoffLimit: 0