version: 2
updates:
- package-ecosystem: npm
  directory: "/client"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  target-branch: develop
  assignees:
  - jonfairbanks
  versioning-strategy: increase
  ignore:
  - dependency-name: eslint-config-airbnb-base
    versions:
    - "> 13.2.0"
  - dependency-name: ejs
    versions:
    - 3.1.6
- package-ecosystem: npm
  directory: "/server"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  target-branch: develop
  assignees:
  - jonfairbanks
  versioning-strategy: increase
  ignore:
  - dependency-name: eslint-config-airbnb-base
    versions:
    - "> 13.2.0"
