name: "Scraper - Build"
# SECRETS NEEDED:
# DOCKER_USERNAME - Container Registry Username (github or dockerhub)
# DOCKER_ACCESS_TOKEN - Container registry Personal access token with push priveledges

on:
  pull_request:
    branches:
      - "master"
    paths:
    - 'scraper/**'

jobs:
  build:
    name: "Scraper - Build"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scraper
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    steps:


      - name: Checkout source code
        uses: "actions/checkout@v2"
        with:
          ref: ${{ github.ref }}

      - name: Build & Push Docker Image
        id: docker-build
        uses: docker/build-push-action@v2
        with:
          context: ./scraper
          file: ./scraper/Dockerfile
          push: false
          tags: ${{ steps.tag-images.outputs.tags }}


