name: "list-subs - Release"
# SECRETS NEEDED:
# DOCKER_USERNAME - Container Registry Username (github or dockerhub)
# DOCKER_ACCESS_TOKEN - Container registry Personal access token with push priveledges

on:
  push:
    branches:
      - "master"
    paths:
    - 'list-subs/**'

jobs:
  release:
    name: "API - Build and Publish"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./list-subs
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      
    steps:
      - uses: act10ns/slack@v1
        with:
          status: starting

      - name: Checkout source code
        uses: "actions/checkout@v2"
        with:
          ref: ${{ github.ref }}

      - name: Update version in version files
        id: update-versions
        run: |
          # Bump version
          npm version --no-git-tag-version patch
          # Get new bumped version
          PACKAGE_VERSION=$(cat package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[",]//g' | tr -d '[[:space:]]')
          # Output new version for other steps
          echo "::set-output name=version::$PACKAGE_VERSION"

      - name: Commit changes
        uses: EndBug/add-and-commit@v7.2.1
        with:
          message: 'Bump to: ${{ steps.update-versions.outputs.version }}'
          tag: '${{ steps.update-versions.outputs.version }}'
          push: 'origin ${{ github.event.repository.default_branch }} --force'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Image Tag(s)
        id: tag-images
        run: |
          if [[ ${{ steps.update-versions.outputs.version }} =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
            TAGS="fairbanksio/f5oclock-list-subs:${{ steps.update-versions.outputs.version }},fairbanksio/f5oclock-list-subs:latest"
          else
            TAGS="fairbanksio/f5oclock-list-subs:latest"
          fi
          echo "::set-output name=tags::${TAGS}"

      - name: Run openfaas-cli build for node16 and shrinkwrap
        uses: docker://openfaas/faas-cli:latest-root
        with:
          args: build --shrinkwrap --image fairbanksio/f5oclock-list-subs --handler=./list-subs --name f5oclock-list-subs --lang=node16

      - name: Login to DockerHub
        if: success()
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push the OpenFaaS function
        uses: docker/build-push-action@v2
        with:
          context: ./build/f5oclock-list-subs/
          file: ./build/f5oclock-list-subs/Dockerfile
          push: true
          tags: ${{ steps.tag-images.outputs.tags }}

      - name: Initiate Helm sync
        id: helm-sync
        uses: benc-uk/workflow-dispatch@v1
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          repo: fairbanks-io/helm-charts
          workflow: Helm repo index

      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
        if: always()

