name: "Scraper - Release"
# SECRETS NEEDED:
# DOCKER_USERNAME - Container Registry Username (github or dockerhub)
# DOCKER_ACCESS_TOKEN - Container registry Personal access token with push priveledges

on:
  push:
    branches:
      - "master"
    paths:
    - 'scraper/**'

jobs:
  release:
    name: "Scraper - Build and Publish"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scraper
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    steps:
      - uses: act10ns/slack@v1
        with:
          status: starting

      - name: Checkout source code
        uses: "actions/checkout@v2"
        with:
          ref: ${{ github.ref }}

      - name: Update version in version files
        id: update-versions
        run: |
          # Bump version
          npm version --no-git-tag-version patch
          # Get new bumped version
          PACKAGE_VERSION=$(cat package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[",]//g' | tr -d '[[:space:]]')
          # Output new version for other steps
          echo "::set-output name=version::$PACKAGE_VERSION"
          
      - name: Commit changes
        uses: EndBug/add-and-commit@v7.2.1
        with:
          message: "Bump to: ${{ steps.update-versions.outputs.version }}"
          tag: "${{ steps.get-version.outputs.version }}"
          push: "origin ${{ github.event.repository.default_branch }} --force"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Image Tag(s)
        id: tag-images
        run: |
          if [[ ${{ steps.update-versions.outputs.version }} =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
            TAGS="fairbanksio/f5oclock-client:${{ steps.update-versions.outputs.version }},fairbanksio/f5oclock-client:latest"
          else
            TAGS="fairbanksio/f5oclock-client:latest"
          fi
          echo "::set-output name=tags::${TAGS}"

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build & Push Docker Image
        id: docker-build
        uses: docker/build-push-action@v2
        with:
          context: ./scraper
          file: ./scraper/Dockerfile
          push: true
          tags: ${{ steps.tag-images.outputs.tags }}

      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
        if: always()
