name: "API - Release"
# SECRETS NEEDED:
# DOCKER_USERNAME - Container Registry Username (github or dockerhub)
# DOCKER_ACCESS_TOKEN - Container registry Personal access token with push priveledges

on:
  push:
    branches:
      - "master"
    paths:
    - 'api/**'

jobs:
  release:
    name: "API - Build and Publish"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      
    steps:

      - name: Checkout source code
        uses: "actions/checkout@v2"
        with:
          ref: ${{ github.ref }}

      - name: Update version in version files
        id: update-versions
        run: |
          # Bump version
          npm version --no-git-tag-version patch
          # Get new bumped version
          PACKAGE_VERSION=$(cat package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[",]//g' | tr -d '[[:space:]]')
          # Update chart version
          sed -r -i "s/(version:[^*]|appVersion:[^*])([[:alnum:].]*)/\1$PACKAGE_VERSION/g" ./chart/Chart.yaml
          # Output new version for other steps
          echo "::set-output name=version::$PACKAGE_VERSION"
          
      - name: Commit changes
        uses: EndBug/add-and-commit@v7.2.1
        with:
          message: "Bump to: ${{ steps.update-versions.outputs.version }}"
          tag: "${{ steps.get-version.outputs.version }}"
          push: "origin ${{ github.event.repository.default_branch }} --force"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Image Tag(s)
        id: tag-images
        run: |
          if [[ ${{ steps.update-versions.outputs.version }} =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
            TAGS="fairbanksio/f5oclock-api:${{ steps.update-versions.outputs.version }},fairbanksio/f5oclock-api:latest"
          else
            TAGS="fairbanksio/f5oclock-api:latest"
          fi
          echo "::set-output name=tags::${TAGS}"

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build & Push Docker Image
        id: docker-build
        uses: docker/build-push-action@v2
        with:
          context: ./api
          file: ./api/Dockerfile
          push: true
          tags: ${{ steps.tag-images.outputs.tags }}

      - name: Initiate Helm sync
        id: helm-sync
        uses: benc-uk/workflow-dispatch@v1
        with:
          ref: refs/heads/main
          token: ${{ secrets.PERSONAL_TOKEN }}
          repo: fairbanksio/helm-charts
          workflow: Helm repo index

