name: Build and Publish

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: 'actions/checkout@v2'
        with:
          ref: ${{ github.ref }}

      - name: Update version in version files
        id: update-version
        run: |
          # Bump version
          npm version --no-git-tag-version patch
          # Get new bumped version
          PACKAGE_VERSION=$(cat package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[",]//g' | tr -d '[[:space:]]')
          # Output new version for other steps
          echo "::set-output name=version::$PACKAGE_VERSION"

      - name: Commit changes
        uses: EndBug/add-and-commit@v7.2.1
        with:
          message: 'Bump to: ${{ steps.update-version.outputs.version }}'
          tag: '${{ steps.get-version.outputs.version }}'
          push: 'origin ${{ github.event.repository.default_branch }} --force'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to DockerHub
        if: success()
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build & Push Docker Image
        id: docker-build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: 'fairbanksio/f5-fetch-data:${{ steps.update-version.outputs.version }}'